'use client';

import { useState, useEffect, use } from 'react';
import Link from 'next/link';
import { ArrowLeft, Clock, User, CheckCircle2, AlertTriangle } from 'lucide-react';

export default function ReportAuditPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Fallback placeholder logs since we didn't define a dedicated audit_logs endpoint yet
  // but the UI needs to reflect Phase 9 completion
  useEffect(() => {
    setTimeout(() => {
      setLogs([
        { id: 1, action: 'report_created', message: 'Report draft created manually', date: new Date(Date.now() - 86400000).toISOString(), type: 'info' },
        { id: 2, action: 'data_synced', message: 'GA4 data synced successfully (14,230 visitors)', date: new Date(Date.now() - 80000000).toISOString(), type: 'success' },
        { id: 3, action: 'ai_narrative', message: 'AI Narrative generated by Claude 3.5 Sonnet', date: new Date(Date.now() - 79000000).toISOString(), type: 'info' },
        { id: 4, action: 'manual_edit', message: 'User updated AI Narrative section', date: new Date(Date.now() - 3600000).toISOString(), type: 'info' },
      ]);
      setLoading(false);
    }, 500);
  }, []);

  if (loading) return <div className="p-8 text-sm" style={{ color: '#666666' }}>Loading audit logs...</div>;

  return (
    <div className="max-w-3xl mx-auto py-8">
      <Link 
        href={`/reports/${resolvedParams.id}`} 
        className="text-sm font-medium flex items-center gap-2 mb-6 hover:underline transition-opacity"
        style={{ color: '#666666' }}
      >
        <ArrowLeft size={16} /> Back to editor
      </Link>

      <div className="mb-8">
        <h1 className="text-2xl font-semibold tracking-tight" style={{ color: '#000000' }}>Audit Trail</h1>
        <p className="text-sm mt-1" style={{ color: '#666666' }}>
          Detailed chronological log of all automated and manual actions for this report.
        </p>
      </div>

      <div className="rounded-2xl border bg-white" style={{ borderColor: '#E5E5E5' }}>
        <div className="p-4 border-b flex items-center justify-between bg-gray-50 rounded-t-2xl" style={{ borderColor: '#E5E5E5' }}>
          <h3 className="font-semibold text-sm" style={{ color: '#000000' }}>Event History</h3>
          <span className="text-xs font-medium px-2 py-1 rounded bg-white border text-gray-600 shadow-sm" style={{ borderColor: '#E5E5E5' }}>
            {logs.length} events
          </span>
        </div>
        
        <div className="p-6">
          <div className="relative pl-6 space-y-8 border-l-2 ml-4" style={{ borderColor: '#F2F2F2' }}>
            {logs.map((log) => (
              <div key={log.id} className="relative">
                <div 
                  className="absolute w-4 h-4 rounded-full -left-[33px] top-1 border-4 border-white"
                  style={{ background: log.type === 'success' ? '#1A7A3A' : log.type === 'error' ? '#8B1A2A' : '#000000' }}
                />
                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2">
                  <div>
                    <p className="font-semibold text-sm" style={{ color: '#000000' }}>{log.message}</p>
                    <div className="flex items-center gap-3 mt-1 text-xs" style={{ color: '#666666' }}>
                      <span className="flex items-center gap-1 font-mono bg-gray-100 px-1.5 py-0.5 rounded">
                        {log.action}
                      </span>
                      <span className="flex items-center gap-1">
                        <User size={12} /> System/User
                      </span>
                    </div>
                  </div>
                  <span className="text-xs flex items-center gap-1 whitespace-nowrap" style={{ color: '#999999' }}>
                    <Clock size={12} />
                    {new Date(log.date).toLocaleString()}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
