'use client';
import { useState } from 'react';
import { Button }     from '@/components/ui/button';
import { Badge }      from '@/components/ui/badge';
import { MetricCard } from '@/components/ui/MetricCard';
import { Card }       from '@/components/ui/card';
import { AlertTriangle, CheckCircle, RotateCcw, Info } from 'lucide-react';
import Link from 'next/link';

export default function ReportReviewPage({ params }: { params: { id: string } }) {
  const [narrative, setNarrative] = useState('');
  const [approving, setApproving] = useState(false);

  // Suppress unused param warning until wired to real data
  void params;

  return (
    <div className="space-y-6">
      {/* Breadcrumb + actions */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-[13px] text-[var(--text-muted)] mb-1">
            <Link href="/dashboard/reports" className="hover:text-[var(--text-primary)] transition-colors">
              Reports
            </Link>
            <span>/</span>
            <span className="text-[var(--text-secondary)]">Client Name</span>
            <span>/</span>
            <span className="text-[var(--text-primary)]">March 2025</span>
          </div>
          <h1 className="text-[24px] font-semibold text-[var(--text-primary)] tracking-[-0.01em]">
            Report Review
          </h1>
        </div>
        <div className="flex items-center gap-3 shrink-0 flex-wrap justify-end">
          <Badge className="bg-amber-100 text-amber-800 hover:bg-amber-100 border-transparent shadow-none">Draft — Awaiting Approval</Badge>
          <Button variant="ghost" size="sm" id="reject-btn" className="gap-2">
            <RotateCcw size={14} /> Reject &amp; Regenerate
          </Button>
          <Button
            size="default"
            disabled={approving}
            onClick={() => setApproving(true)}
            id="approve-btn"
            className="gap-2"
          >
            <CheckCircle size={16} /> {approving ? 'Approving...' : 'Approve & Send'}
          </Button>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="grid lg:grid-cols-[1fr_360px] gap-6">
        {/* Narrative editor */}
        <div className="space-y-4">
          <Card>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-[16px] font-semibold text-[var(--text-primary)]">AI Narrative</h2>
              <span className="text-[12px] text-[var(--text-muted)]">Edit freely before approving</span>
            </div>
            <textarea
              value={narrative}
              onChange={e => setNarrative(e.target.value)}
              placeholder="AI narrative will appear here after generation..."
              id="narrative-editor"
              className="
                w-full min-h-[300px] p-4 rounded-[var(--radius-md)]
                bg-[var(--bg-surface)] border border-[var(--border)]
                text-[15px] text-[var(--text-primary)] leading-[1.7]
                placeholder:text-[var(--text-placeholder)]
                resize-none
                focus:outline-none focus:border-[var(--accent)] focus:shadow-[var(--shadow-focus)]
                transition-all duration-[120ms] ease-[ease]
              "
            />
            <div className="flex items-center justify-between mt-3">
              <span className="text-[12px] text-[var(--text-muted)]">{narrative.length} / 10,000 characters</span>
              <div className="flex items-center gap-1.5 text-[12px] text-[var(--text-muted)]">
                <Info size={12} strokeWidth={1.5} />
                This is what your client receives
              </div>
            </div>
          </Card>

          <Card className="p-4">
            <div className="flex items-center gap-4 flex-wrap">
              <div className="flex items-center gap-2">
                <span className="text-[12px] text-[var(--text-muted)]">Overall confidence:</span>
                <Badge className="bg-green-100 text-green-800 hover:bg-green-100 border-transparent shadow-none">High Confidence</Badge>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[12px] text-[var(--text-muted)]">Generated by:</span>
                <span className="text-[12px] font-medium text-[var(--text-secondary)] bg-[var(--bg-surface)] border border-[var(--border)] px-2 py-0.5 rounded-md">
                  Claude Haiku
                </span>
              </div>
            </div>
          </Card>
        </div>

        {/* Metrics column */}
        <div className="space-y-3">
          <h2 className="text-[15px] font-semibold text-[var(--text-primary)]">Verified Metrics</h2>
          <MetricCard label="Sessions"    value="12,450" delta={22.1} source="Google Analytics" confidence="high" />
          <MetricCard label="Users"       value="9,830"  delta={21.4} source="Google Analytics" confidence="high" />
          <MetricCard label="Bounce Rate" value="42.3%"  delta={-6.2} source="Google Analytics" confidence="high" />
          <MetricCard label="Avg Session" value="3m 07s" delta={13.3} source="Google Analytics" confidence="high" />

          {/* Data warning */}
          <div className="flex items-start gap-3 p-3 rounded-[var(--radius-md)] bg-[var(--warning-bg)] border border-[var(--warning)]/20">
            <AlertTriangle size={14} className="text-[var(--warning)] mt-0.5 shrink-0" strokeWidth={1.5} />
            <div>
              <p className="text-[12px] font-medium text-[var(--warning-text)]">Preliminary data</p>
              <p className="text-[12px] text-[var(--warning-text)]/80">
                Bounce rate may take up to 48 hours to finalize in Google Analytics.
              </p>
            </div>
          </div>

          <p className="text-[11px] text-[var(--text-muted)] text-center pt-2">
            Last updated from Google Analytics: 2 hours ago
          </p>
        </div>
      </div>
    </div>
  );
}
