'use client';

import { motion } from 'framer-motion';
import { ShieldCheck, FileText, Palette, FileSearch } from 'lucide-react';
import { slideLeft, slideRight } from '@/lib/animations';

const features = [
  {
    icon: ShieldCheck,
    tag: 'Data integrity',
    title: 'Every number verified before it leaves our system',
    body: 'Reportly runs automated validation on every metric. Anomalies are flagged. Outliers are checked against prior periods. We\'d rather delay a report than send a wrong one.',
    side: 'left' as const,
    visual: (
      <div className="rounded-3xl p-8 space-y-4 shadow-2xl" style={{ background: '#FDFDFD', boxShadow: '0 20px 50px rgba(0,0,0,0.04)' }}>
        {['Sessions: 12,430', 'Users: 8,291', 'Bounce Rate: 42.1%', 'Avg. Session: 2m 14s'].map((m, i) => (
          <div key={i} className="flex items-center justify-between text-sm py-3 px-4 rounded-xl transition-colors hover:bg-gray-50" style={{ background: 'rgba(0,0,0,0.02)' }}>
            <span className="font-semibold" style={{ color: '#000000' }}>{m}</span>
            <span className="text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-wider" style={{ background: '#1A7A3A', color: '#FFFFFF' }}>Verified</span>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: FileText,
    tag: 'AI narrative',
    title: 'An analyst-quality write-up, every time',
    body: 'Claude Haiku reads your data and writes a narrative that explains what happened, why it happened, and what to do next. Edit it in our TipTap editor, or approve it as-is.',
    side: 'right' as const,
    visual: (
      <div className="rounded-3xl p-10 shadow-2xl" style={{ background: '#FFFFFF', boxShadow: '0 20px 50px rgba(0,0,0,0.04)' }}>
        <p className="text-[10px] font-bold mb-4 uppercase tracking-[0.2em]" style={{ color: '#AAAAAA' }}>AI Narrative — March 2026</p>
        <p className="text-base leading-relaxed font-medium" style={{ color: '#000000' }}>
          Organic search drove a <strong className="font-black text-green-600">23% increase in sessions</strong> this month, led by a strong performance in branded keywords. The new landing pages from the February campaign contributed 18% of new user acquisition...
        </p>
        <div className="flex items-center gap-2.5 mt-6 pt-6 border-t border-gray-100">
          <div className="w-2.5 h-2.5 rounded-full" style={{ background: '#000000' }} />
          <span className="text-[10px] font-bold uppercase tracking-widest" style={{ color: '#777777' }}>Generated by Gemini 1.5 Flash</span>
        </div>
      </div>
    ),
  },
  {
    icon: Palette,
    tag: 'White-label',
    title: 'Your brand. Your colors. Your footer.',
    body: 'Upload your logo, set your brand colors, choose a PDF layout, and customise every section. Your clients never need to know Reportly exists.',
    side: 'left' as const,
    visual: (
      <div className="rounded-3xl overflow-hidden shadow-2xl" style={{ boxShadow: '0 20px 50px rgba(0,0,0,0.05)' }}>
        <div className="px-8 py-6 flex items-center gap-4" style={{ background: '#000000' }}>
          <div className="w-7 h-7 rounded-lg bg-white/20" />
          <span className="text-base font-black text-white tracking-tight">Pixel Digital Agency</span>
        </div>
        <div className="p-10 space-y-6" style={{ background: '#FFFFFF' }}>
          <div className="h-4 rounded-full w-3/4 opacity-10" style={{ background: '#000000' }} />
          <div className="h-4 rounded-full w-full opacity-10" style={{ background: '#000000' }} />
          <div className="h-4 rounded-full w-2/3 opacity-10" style={{ background: '#000000' }} />
          <div className="grid grid-cols-3 gap-4 mt-6">
            {['Sessions','Users','Bounce'].map((k) => (
              <div key={k} className="rounded-2xl p-4 text-center" style={{ background: '#F9F9F9' }}>
                <p className="text-xl font-black" style={{ color: '#000000' }}>—</p>
                <p className="text-[10px] font-bold uppercase tracking-wider mt-1 opacity-40" style={{ color: '#000000' }}>{k}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    ),
  },
  {
    icon: FileSearch,
    tag: 'Audit trail',
    title: 'A full audit log for every report',
    body: 'Every fetch, every AI call, every edit, every approval is logged with a timestamp and actor. When a client questions a number, you have receipts.',
    side: 'right' as const,
    visual: (
      <div className="rounded-3xl p-10 shadow-2xl" style={{ background: '#FFFFFF', boxShadow: '0 20px 50px rgba(0,0,0,0.04)' }}>
        {[
          { time: '02:14', event: 'Data fetched from GA4', actor: 'Cron' },
          { time: '02:15', event: 'Validation passed', actor: 'System' },
          { time: '02:16', event: 'AI narrative generated', actor: 'Gemini' },
          { time: '09:31', event: 'Narrative edited by Priya', actor: 'User' },
          { time: '09:45', event: 'Approved and sent', actor: 'Priya' },
        ].map((e, i) => (
          <div key={i} className="flex gap-5 text-sm py-4 border-b last:border-0 border-gray-50">
            <span className="w-14 flex-shrink-0 font-bold opacity-30" style={{ color: '#000000' }}>{e.time}</span>
            <span className="flex-1 font-bold" style={{ color: '#000000' }}>{e.event}</span>
            <span className="text-[10px] font-black uppercase tracking-widest opacity-40" style={{ color: '#000000' }}>{e.actor}</span>
          </div>
        ))}
      </div>
    ),
  },
];

export function Features() {
  return (
    <section className="marketing-section py-20" style={{ background: '#FFFFFF' }}>
      <div className="mx-auto w-full max-w-5xl px-6 md:px-[100px] space-y-16">
        {/* Header */}
        <div className="text-center" style={{ maxWidth: 640, margin: '0 auto' }}>
          <p className="text-[9px] font-black tracking-[0.3em] uppercase mb-3" style={{ color: '#AAAAAA' }}>
            The Platform
          </p>
          <h2 className="text-2xl md:text-3xl font-black tracking-tight leading-tight" style={{ color: '#000000' }}>
            Built for agencies that care about quality
          </h2>
        </div>

        {/* Feature rows */}
        {features.map((f, i) => {
          const Icon = f.icon;
          const isRight = f.side === 'right';
          return (
            <div
              key={i}
              className={`grid md:grid-cols-2 gap-10 md:gap-14 items-center ${isRight ? 'md:[&>*:first-child]:order-2' : ''}`}
            >
              <motion.div
                variants={isRight ? slideRight : slideLeft}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.25 }}
                className="flex flex-col gap-4"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-lg flex items-center justify-center shadow-md" style={{ background: '#000000' }}>
                    <Icon size={16} color="#FFFFFF" strokeWidth={2.5} />
                  </div>
                  <span className="text-[9px] font-black tracking-[0.2em] uppercase opacity-40" style={{ color: '#000000' }}>
                    {f.tag}
                  </span>
                </div>
                <h3 className="text-xl md:text-2xl font-black tracking-tight leading-tight" style={{ color: '#000000' }}>
                  {f.title}
                </h3>
                <p className="text-sm leading-relaxed font-medium opacity-40" style={{ color: '#000000' }}>
                  {f.body}
                </p>
              </motion.div>

              <motion.div
                variants={isRight ? slideLeft : slideRight}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.25 }}
              >
                <div className="scale-90 md:scale-100 origin-center">
                  {f.visual}
                </div>
              </motion.div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
