'use client';

import { motion } from 'framer-motion';
import { ShieldCheck, FileText, Palette, FileSearch } from 'lucide-react';
import { slideLeft, slideRight } from '@/lib/animations';

const features = [
  {
    icon: ShieldCheck,
    tag: 'Data integrity',
    title: 'Every number verified before it leaves our system',
    body: 'Reportly runs automated validation on every metric. Anomalies are flagged. Outliers are checked against prior periods. We\'d rather delay a report than send a wrong one.',
    side: 'left' as const,
    visual: (
      <div className="rounded-2xl p-6 space-y-3" style={{ background: '#F8F8F8', border: '1px solid #E5E5E5' }}>
        {['Sessions: 12,430', 'Users: 8,291', 'Bounce Rate: 42.1%', 'Avg. Session: 2m 14s'].map((m, i) => (
          <div key={i} className="flex items-center justify-between text-sm py-2 border-b last:border-0" style={{ borderColor: '#EEEEEE' }}>
            <span style={{ color: '#555555' }}>{m}</span>
            <span className="text-xs font-medium px-2 py-0.5 rounded-full" style={{ background: '#F0FAF4', color: '#1A7A3A' }}>Verified</span>
          </div>
        ))}
      </div>
    ),
  },
  {
    icon: FileText,
    tag: 'AI narrative',
    title: 'An analyst-quality write-up, every time',
    body: 'Claude Haiku reads your data and writes a narrative that explains what happened, why it happened, and what to do next. Edit it in our TipTap editor, or approve it as-is.',
    side: 'right' as const,
    visual: (
      <div className="rounded-2xl p-6" style={{ background: '#F8F8F8', border: '1px solid #E5E5E5' }}>
        <p className="text-xs font-medium mb-3" style={{ color: '#999999' }}>AI Narrative — March 2025</p>
        <p className="text-sm leading-relaxed" style={{ color: '#333333' }}>
          Organic search drove a <strong>23% increase in sessions</strong> this month, led by a strong performance in branded keywords. The new landing pages from the February campaign contributed 18% of new user acquisition...
        </p>
        <div className="flex items-center gap-2 mt-4">
          <span className="w-2 h-2 rounded-full" style={{ background: '#000000' }} />
          <span className="text-xs" style={{ color: '#999999' }}>Generated by Claude Haiku</span>
        </div>
      </div>
    ),
  },
  {
    icon: Palette,
    tag: 'White-label',
    title: 'Your brand. Your colors. Your footer.',
    body: 'Upload your logo, set your brand colors, choose a PDF layout, and customise every section. Your clients never need to know Reportly exists.',
    side: 'left' as const,
    visual: (
      <div className="rounded-2xl overflow-hidden" style={{ border: '1px solid #E5E5E5' }}>
        <div className="px-6 py-4 flex items-center gap-3" style={{ background: '#000000' }}>
          <div className="w-6 h-6 rounded bg-white/20" />
          <span className="text-sm font-medium text-white">Pixel Digital Agency</span>
        </div>
        <div className="p-6 space-y-4" style={{ background: '#F8F8F8' }}>
          <div className="h-3 rounded-full w-3/4" style={{ background: '#E5E5E5' }} />
          <div className="h-3 rounded-full w-full" style={{ background: '#E5E5E5' }} />
          <div className="h-3 rounded-full w-2/3" style={{ background: '#E5E5E5' }} />
          <div className="flex gap-3 mt-4">
            {['Sessions','Users','Bounce'].map((k) => (
              <div key={k} className="flex-1 rounded-xl p-3 text-center" style={{ background: '#FFFFFF', border: '1px solid #E5E5E5' }}>
                <p className="text-base font-bold" style={{ color: '#000000' }}>—</p>
                <p className="text-xs" style={{ color: '#999999' }}>{k}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    ),
  },
  {
    icon: FileSearch,
    tag: 'Audit trail',
    title: 'A full audit log for every report, every time',
    body: 'Every fetch, every AI call, every edit, every approval is logged with a timestamp and actor. When a client questions a number, you have receipts.',
    side: 'right' as const,
    visual: (
      <div className="rounded-2xl p-6" style={{ background: '#F8F8F8', border: '1px solid #E5E5E5' }}>
        {[
          { time: '02:14', event: 'Data fetched from GA4', actor: 'Cron' },
          { time: '02:15', event: 'Validation passed (12 checks)', actor: 'System' },
          { time: '02:16', event: 'AI narrative generated', actor: 'Claude' },
          { time: '09:31', event: 'Narrative edited by Priya', actor: 'User' },
          { time: '09:45', event: 'Approved and sent', actor: 'Priya' },
        ].map((e, i) => (
          <div key={i} className="flex gap-4 text-xs py-2 border-b last:border-0" style={{ borderColor: '#EEEEEE' }}>
            <span className="w-12 flex-shrink-0" style={{ color: '#AAAAAA' }}>{e.time}</span>
            <span className="flex-1" style={{ color: '#333333' }}>{e.event}</span>
            <span style={{ color: '#999999' }}>{e.actor}</span>
          </div>
        ))}
      </div>
    ),
  },
];

export function Features() {
  return (
    <section className="marketing-section" style={{ background: '#FFFFFF' }}>
      <div className="container space-y-24">
        {/* Header */}
        <div className="text-center" style={{ maxWidth: 640, margin: '0 auto' }}>
          <p className="text-xs font-semibold tracking-widest uppercase mb-4" style={{ color: '#777777' }}>
            What you get
          </p>
          <h2 className="text-4xl md:text-5xl font-semibold tracking-tight" style={{ color: '#000000' }}>
            Built for agencies that care about quality
          </h2>
        </div>

        {/* Feature rows */}
        {features.map((f, i) => {
          const Icon = f.icon;
          const isRight = f.side === 'right';
          return (
            <div
              key={i}
              className={`grid md:grid-cols-2 gap-12 md:gap-16 items-center ${isRight ? 'md:[&>*:first-child]:order-2' : ''}`}
            >
              <motion.div
                variants={isRight ? slideRight : slideLeft}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.25 }}
                className="flex flex-col gap-5"
              >
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#000000' }}>
                    <Icon size={14} color="#FFFFFF" />
                  </div>
                  <span className="text-xs font-semibold tracking-widest uppercase" style={{ color: '#777777' }}>
                    {f.tag}
                  </span>
                </div>
                <h3 className="text-2xl md:text-3xl font-semibold tracking-tight" style={{ color: '#000000' }}>
                  {f.title}
                </h3>
                <p className="text-base leading-relaxed" style={{ color: '#666666' }}>
                  {f.body}
                </p>
              </motion.div>

              <motion.div
                variants={isRight ? slideLeft : slideRight}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, amount: 0.25 }}
              >
                {f.visual}
              </motion.div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
