import { ValidatedMetricSet } from '@/types/metrics';
import { Agency, Report } from '@/types/report';

export function getReportHtml(
  report: Report,
  agency: Agency,
  metrics: ValidatedMetricSet,
  narrative: string
): string {
  const brandColor = agency.brand_color || '#3b82f6';
  const logoUrl = agency.logo_url || 'https://via.placeholder.com/150?text=Reportly';

  const metricRows = Object.entries(metrics.validated).map(([key, mv]) => `
    <div class="metric-card">
      <div class="metric-label">${key.toUpperCase()}</div>
      <div class="metric-value">${mv.value?.toLocaleString() || 'N/A'}</div>
      <div class="metric-delta ${mv.delta && mv.delta > 0 ? 'up' : 'down'}">
        ${mv.delta !== null ? (mv.delta > 0 ? 'â–²' : 'â–¼') + ' ' + Math.abs(mv.delta).toFixed(1) + '%' : ''}
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
        body { font-family: 'Inter', sans-serif; margin: 0; padding: 40px; color: #1f2937; line-height: 1.5; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid ${brandColor}; padding-bottom: 20px; margin-bottom: 40px; }
        .logo { height: 50px; }
        .agency-info { text-align: right; }
        .report-title { font-size: 28px; font-weight: 700; margin: 0; color: ${brandColor}; }
        .period { color: #6b7280; font-size: 14px; }
        .section-title { font-size: 20px; font-weight: 600; margin: 40px 0 20px 0; border-left: 4px solid ${brandColor}; padding-left: 12px; }
        .metrics-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
        .metric-card { padding: 20px; background: #f9fafb; border-radius: 8px; border: 1px solid #e5e7eb; }
        .metric-label { font-size: 12px; font-weight: 600; color: #6b7280; text-transform: uppercase; }
        .metric-value { font-size: 24px; font-weight: 700; margin: 8px 0; }
        .metric-delta { font-size: 14px; font-weight: 600; }
        .metric-delta.up { color: #10b981; }
        .metric-delta.down { color: #ef4444; }
        .narrative { font-size: 16px; white-space: pre-wrap; color: #374151; }
        .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 20px; }
      </style>
    </head>
    <body>
      <div class="header">
        <img src="${logoUrl}" class="logo" />
        <div class="agency-info">
          <div class="report-title">Performance Report</div>
          <div class="period">Period: ${new Date(metrics.periodStart).toLocaleDateString()} - ${new Date(metrics.periodEnd).toLocaleDateString()}</div>
        </div>
      </div>

      <div class="section-title">Executive Summary</div>
      <div class="narrative">${narrative}</div>

      <div class="section-title">Key Performance Indicators</div>
      <div class="metrics-grid">
        ${metricRows}
      </div>

      <div class="footer">
        Generated by Reportly for ${agency.name}
      </div>
    </body>
    </html>
  `;
}
